core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path('', include('appves.urls')),
    path('admin/', admin.site.urls),
    path('appves/', include('appves.urls')),
    path('user/', include('user.urls')),
]

# Se agrega para que se pueda ver el contenido de la carpeta static
urlpatterns += staticfiles_urlpatterns()

# Configuracion para poder ver las imagenes en el navegador
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user import views
from .views import CrearAvistaje, ListarAvistajes, EliminarAvistaje


urlpatterns = [
  
    path('quienes/', views.quienes, name='quienes'),
    path('create_user/', views.create_user, name='create_user'),
    path('login_user/', views.login_user, name='login'),
    path('logout_user/', views.logout_user, name='logout'),
    path("contacto/", views.contacto, name="contacto"),
  
    path('create_list/<int:pk>', CrearAvistaje.as_view(), name='crear_avistaje'),
    path('list_avistaje/', ListarAvistajes.as_view(), name='listar_avistajes'),
    path('eliminar/<int:pk>', EliminarAvistaje.as_view(), name='eliminar_avistaje'),
]

user/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.utils import timezone


# Create your models here.
class Province(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class User(AbstractUser):
    image = models.ImageField(default="user_default.png", upload_to="user/")
    province = models.ForeignKey(
        Province, on_delete=models.SET_NULL, null=True, blank=True
    )

    objects = UserManager()


class Avistaje(models.Model):
    id_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    nombre_avistaje = models.CharField(max_length=50, null=False)
    fecha_creacion = models.DateTimeField(default=timezone.now)
    activo = models.BooleanField(default=True)


class Contacto(models.Model):
    nombre = models.CharField(max_length=50, null=False)
    username = models.CharField(max_length=50, null=True)
    email = models.EmailField(max_length=254, null=False)
    mensaje = models.TextField(max_length=500, null=False)
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Avistaje, Province

class UserLoginForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(
            attrs={
                'id': 'username',
                'type': 'text',
                'class': 'form-control'
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'password1',
                'type': 'password',
                'class': 'form-control'
            }
        )
    )
    

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'id': 'emailRegister',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(
            attrs={
                'id': 'username',
                'type': 'text',
                'class': 'form-control'
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'password1',
                'type': 'password',
                'class': 'form-control'
            }
        )
    )
    password2 = forms.CharField(
        label='Confirmar password',
        widget=forms.PasswordInput(
            attrs={
                'id': 'password2',
                'type': 'password',
                'class': 'form-control'
            }
        )
    )
    image = forms.ImageField(required=False)
    province = forms.ModelChoiceField(required=False, queryset=Province.objects.all())

    class Meta:
        # model = User
        model = get_user_model() # ¡captura el propio modelo de usuario personalizado!
        fields = ("username", "email", "province", "image", "password1", "password2")

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        #user.province = self.cleaned_data["province"]
        #user.image = self.cleaned_data["image"]
        if commit:
            user.save()
        return user

class AvistajeForm(forms.ModelForm):
    activo = forms.BooleanField(initial=True)
    class Meta:
        model = Avistaje
        fields = "__all__"

user/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin

# from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView

from .forms import AvistajeForm, CustomUserCreationForm, UserLoginForm
from .models import Avistaje, Contacto


def quienes(request):
    return render(request, "user/quienes.html")


def create_user(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Te has registrado con éxito")
            username = request.POST["username"]
            password = request.POST["password1"]
            user = authenticate(request, username=username, password=password)
            login(request, user=user)
            return redirect("home")
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field.capitalize()}: {error}")
    else:
        form = CustomUserCreationForm()
    return render(request, "user/create_user.html", {"form": form})


def login_user(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user=user)
                messages.success(request, "¡Inicio de sesión exitoso!")
                return redirect("home")
            else:
                messages.error(request, "Usuario o contraseña incorrectos")
    else:
        form = UserLoginForm()
    return render(request, "user/login_user.html", {"form": form})


def logout_user(request):
    logout(request)
    messages.success(request, "¡Cierre de sesión exitoso!")
    return redirect("home")


def contacto(request):
    if request.method == "POST":
        contacto = Contacto()
        nombre = request.POST.get("nombre")
        username = request.POST.get("username")
        email = request.POST.get("email")
        mensaje = request.POST.get("mensaje")
        contacto.nombre = nombre
        contacto.username = username
        contacto.email = email
        contacto.mensaje = mensaje
        contacto.save()
        messages.success(request, "Mensaje enviado con éxito, Gracias por contactarnos")
        return redirect("home")
    return render(request, "user/contacto.html")


class CrearAvistaje(LoginRequiredMixin, CreateView):
    model = Avistaje
    form_class = AvistajeForm
    template_name = "user/crear_lista.html"
    success_url = reverse_lazy("listar_avistajes")

    def get_initial(self):
        return {"id_user": self.kwargs["pk"]}


class ListarAvistajes(LoginRequiredMixin, ListView):
    model = Avistaje
    template_name = "user/lista_avistajes.html"
    context_object_name = "avistajes"

    def get_queryset(self):
        self.queryset = Avistaje.objects.filter(id_user_id=self.request.user.pk).filter(activo=True)
        return self.queryset


class EliminarAvistaje(LoginRequiredMixin, DeleteView):
    model = Avistaje
    success_url = reverse_lazy("listar_avistajes")

    def post(self, request, *args, **kwargs):
        avistaje = self.get_object()
        avistaje.activo = False
        avistaje.save()
        return redirect(self.success_url)
        

templates/user/avistaje_confirm_delete.html
{% extends "base.html" %}
{% block title %}
    <title>Confirmación de eliminación</title>
{% endblock title %}
{% load static %}
{% block content %}
    {% block styles %}
        <link rel="stylesheet"
              href="{% static 'css/appves/bird_confirm_delete.css' %}">
    {% endblock styles %}
    <div class="container">
        <form method="post"
              class="mx-auto cont-form col-md-10 formulario-con-borde">
            {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    <h1 class="text-center">Confirmación de eliminación</h1>
                </div>
            </div>
            <p class="text-center">
                <strong>Seguro desea borrar la lista: {{ object.nombre_avistaje }}?</strong>
            </p>
            <div class="text-center">
                <button type="submit" class="btn btn-danger">Confirmar</button>
                <a href="{% url 'listar_avistajes' %}" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/user/contacto.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    <title>Contacto</title>
{% endblock title %}
{% block content %}
    {% block styles %}
        <link rel="stylesheet" href="{% static 'css/user/contacto.css' %}">
    {% endblock styles %}
    <div class="contenedor">
        <form class="form-col" method="post">
            {% csrf_token %}
            <h1>Contacto</h1>
            <div class="form-row">
                <label for="nombre">Nombre</label>
                <input type="text"
                    class="form-control"
                    name="nombre"
                    placeholder=""
                    required
                    autofocus>
            </div>
            <div class="form-row">
                <label for="username">Username</label>
                <input type="text"
                    class="form-control"
                    name="username"
                    placeholder="">
            </div>
            <div class="form-row">
                <label for="femail">Email</label>
                <input type="email"
                    id="femail"
                    name="email"
                    class="form-control"
                    required>
            </div>
            <div class="form-row">
                <label for="mensaje">Mensaje</label>
                <textarea id="fmensaje"
                        name="mensaje"
                        class="form-control"
                        placeholder="-- Ingresa un mensaje --"
                        required></textarea>
            </div>
            <div class="d-flex justify-content-center">
                <input type="submit" class="btn btn-success mt-3">
            </input>
        </div>
    </form>
</div>
{% endblock content %}

templates/user/crear_lista.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% block styles %}
        <link rel="stylesheet" href="{% static 'css/user/crear_lista.css' %}">
    {% endblock styles %}
    <div class="mx-auto cont-form col-md-11 formulario-con-borde">
        <h1>Crear avistaje</h1>
        <form class="form" method="post">
            {% csrf_token %}
            <div class="not-visible">{{ form.id_user }}</div>
            <div class="not-visible">{{ form.activo }}</div>
            <div class="form-group">
                <label for="{{ form.nombre_avistaje.id_for_label }}">Nombre del avistaje</label>
                <input type="text"
                       class="form-control"
                       id="{{ form.nombre_avistaje.id_for_label }}"
                       name="{{ form.nombre_avistaje.html_name }}">
            </div>
            <div class="form-group">
                <label for="{{ form.fecha_creacion.id_for_label }}">Fecha y hora</label>
                <input type="datetime-local"
                       class="form-control"
                       id="{{ form.fecha_creacion.id_for_label }}"
                       name="{{ form.fecha_creacion.html_name }}"
                       value="{{ form.initial.fecha_creacion|default:'' }}">
            </div>
            <button class="btn btn-success mt-3 crear">Crear</button>
        </form>
    </div>
{% endblock content %}

templates/user/create_user.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    <title>Crear cuenta</title>
{% endblock title %}
{% block content %}
    {% block styles %}
        <link rel="stylesheet" href="{% static 'css/user/create_user.css' %}">
        <script src="{% static 'js/modal.js' %}" defer></script>
    {% endblock styles %}
    <div class="contenedor">
        <h1 class="cont-titulo">Crear cuenta</h1>
        {% if messages %}
            <div class="alert alert-danger">
                <ul>
                    {% for message in messages %}<li>{{ message }}</li>{% endfor %}
                </ul>
            </div>
        {% endif %}
        <form class="cont-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="emailRegister">Email</label>
                <input type="email"
                       id="emailRegister"
                       name="email"
                       class="form-control smaller-input"
                       required
                       autofocus>
            </div>
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text"
                       id="username"
                       name="username"
                       class="form-control smaller-input"
                       maxlength="150"
                       required>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <label for="password1">Password</label>
                    <input type="password"
                        id="password1"
                        name="password1"
                        class="form-control smaller-input"
                        required>
                </div>
                <div class="form-check">
                    <input type="checkbox" id="chbxpass" class="form-check-input">
                    <label style="font-size: x-small;" for="chbxpass">Mostrar password</label>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <label for="password2">Confirmar password</label>
                    <input type="password"
                        id="password2"
                        name="password2"
                        class="form-control smaller-input"
                        required>
                </div>
                <div class="form-check">
                    <input type="checkbox" id="chbxpass2" class="form-check-input">
                    <label style="font-size: x-small;" for="chbxpass2">Mostrar confirmacion</label>
                </div>
            </div>
            <div class="form-group not-visible">
                <label for="id_province">Provincia</label>
                <select id="id_province" name="province" class="form-control smaller-input">
                    <option value="">-- Selecciona una provincia --</option>
                    {% for province in form.province.field.queryset %}
                        <option value="{{ province.pk }}"
                                {% if province.pk == form.province.value %}selected{% endif %}>{{ province }}</option>
                    {% endfor %}
                </select>
                {{ form.province.errors }}
            </div>
            <div class="form-group not-visible">
                <label for="id_image">Imagen</label>
                <input id="id_image"
                       type="file"
                       name="image"
                       class="form-control smaller-input">
                {{ form.image.errors }}
            </div>
            <button type="submit" class="btn btn-success mt-4">Crear cuenta</button>
        </form>
    </div>

    <script type="text/javascript" defer>

        var checkpass = document.getElementById("chbxpass");
        var checkpass2 = document.getElementById("chbxpass2");
        var txtpass = document.getElementById("password1");
        var txtpass2 = document.getElementById("password2");
        checkpass.addEventListener('click', ()=> {
            showhide(checkpass, txtpass);
        })
        checkpass2.addEventListener('click', ()=> {
            showhide(checkpass2, txtpass2);
        })

        function showhide(chk, txtinput) {
            console.log(txtinput.type);
        
            if (chk.checked) {
                txtinput.type = "text";
            } else {
                txtinput.type = "password";
            }
        }
    </script>
{% endblock content %}

templates/user/lista_avistajes.html
{% extends "base.html" %}
{% block title %}
    <title>Fichas de Aves</title>
{% endblock title %}
{% load static %}
{% block content %}
    {% block styles %}
        <!-- Option 1: Include in HTML -->
        <link rel="stylesheet" href="{% static 'css/user/lista_avistajes.css' %}">
    {% endblock styles %}
    <div class="text-center formulario-con-borde">
        <h1>Mis listas de Avistaje</h1>
        <form class="form">
            <div class="row mt-2">
            <div class="col-12 col-md-3 d-flex align-items-center justify-content-center"><h3>Nombre</h3></div>
            <div class="col-12 col-md-4 d-flex align-items-center justify-content-center"><h3>Fecha de creacion</h3></div>
            <div class="col-12 col-md-5 d-flex align-items-center justify-content-center"><h3>Acciones</h3></div>
        </div>
            {% for avistaje in avistajes %}
                <div class="row mt-2">
                    <div class="col-12 col-md-3 d-flex align-items-center justify-content-center">{{ avistaje.nombre_avistaje }}</div>
                    <div class="col-12 col-md-4 d-flex align-items-center justify-content-center">{{ avistaje.fecha_creacion }}</div>
                    <div class="col-12 col-md-5 d-flex align-items-center justify-content-center">
                        <a href="{% url 'ver_avistaje' avistaje.id %}"
                           type="button"
                           class="btn btn-secondary"><i class="bi bi-eye"></i></a>
                        <a href="{% url 'cargar_ave_avistaje' avistaje.id %}"
                           type="button"
                           class="btn btn-success"><i class="bi bi-plus"></i></a>
                        <a href="{% url 'eliminar_avistaje' avistaje.id %}" type="button" class="btn btn-danger"><i class="bi bi-trash"></i></a>
                    </div>
                </div>
            {% endfor %}
        </form>
    </div>
{% endblock content %}

templates/user/login_user.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    <title>Login</title>
{% endblock title %}
{% block content %}
    {% block styles %}
        <link rel="stylesheet" href="{% static 'css/user/login_user.css' %}">
    {% endblock styles %}
    <div class="contenedor">
        <h1 class="cont-titulo">Login</h1>
        <form class="cont-form" method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text"
                   class="form-control smaller-input"
                   name="username"
                   placeholder=""
                   required
                   autofocus>
            <label for="password" >Password</label>
            <input type="password"
                class="form-control smaller-input"
                id="txtpass"
                name="password"
                placeholder=""
                required>
            <!-- <div class="form-check"> -->
            <div class="form-check">

                <input type="checkbox" id="chbxpass" class="form-check-input">
                <label style="font-size: x-small;" for="chbxpass" class="form-check label">Mostrar password</label>
            </div>
            <button class="btn btn-success mt-4" type="submit">Login</button>
        </form>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags %}
                    {% if "error" in message.tags %}
                        <script>
                            swal.fire({
                                title: "Error",
                                text: "{{ message }}",
                                icon: "error",
                                timer: 3500
                            });
                        </script>
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
    
    <script type="text/javascript" defer>

        var checkpass = document.getElementById("chbxpass");
        var txtpass = document.getElementById("txtpass");
        checkpass.addEventListener('click', ()=> {
            showhide(checkpass, txtpass);
        })

        function showhide(chk, txtinput) {
            console.log(txtinput.type);
            
            if (chk.checked) {
                txtinput.type = "text";
            } else {
                txtinput.type = "password";
            }
        };
    </script>
{% endblock content %}